version: "3"

volumes:
  mariadb:
  mongodb:
  redis:

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=development
      - MYSQL_USER=app
      - MYSQL_PASSWORD=development
      - MYSQL_DATABASE=app
    volumes:
      - mariadb:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mongodb:
    image: mongo
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
